// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc832.TShirtCannon;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay cannonFirefire;
    public static Relay cannonCompcompressors;
    public static Relay cannonLightlight;
    public static Compressor pneumaticscompressors;
    public static DoubleSolenoid anglePistonlift;
    public static Solenoid angleHoldliftHold;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainleft1;
    public static SpeedController driveTrainleft2;
    public static SpeedController driveTrainright1;
    public static SpeedController driveTrainright2;
    public static RobotDrive driveTraintank;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        cannonFirefire = new Relay(1, 1);
	LiveWindow.addActuator("cannonFire", "fire", cannonFirefire);
        
        cannonCompcompressors = new Relay(1, 3);
	LiveWindow.addActuator("cannonComp", "compressors", cannonCompcompressors);
        
        cannonLightlight = new Relay(1, 2);
	LiveWindow.addActuator("cannonLight", "light", cannonLightlight);
        
        pneumaticscompressors = new Compressor(1, 1, 1, 4);
	
        
        anglePistonlift = new DoubleSolenoid(1, 1, 2);      
	
        
        angleHoldliftHold = new Solenoid(1, 3);
	LiveWindow.addActuator("angleHold", "liftHold", angleHoldliftHold);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
        driveTrainleft1 = new Talon(1, 1);
        driveTrainleft2 = new Talon(1, 3);
        
        driveTrainright1 = new Talon(1, 2);
        driveTrainright2 = new Talon(1, 4);
        
        driveTraintank = new RobotDrive(driveTrainleft1, driveTrainleft2, driveTrainright1, driveTrainright2);
	
        driveTraintank.setSafetyEnabled(false);
        driveTraintank.setExpiration(0.1);
        driveTraintank.setSensitivity(0.5);
        driveTraintank.setMaxOutput(1.0);  
    }
}
