// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc832.TShirtCannon.subsystems;
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.DigitalModule;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class leds extends Subsystem {
     I2C i2c;
     byte[] toSend = new byte[1];
     
    public void initDefaultCommand() {
    }
    
    public void i2csend(byte i) { //Function for sending I2C commands to Arduino
        DigitalModule module = DigitalModule.getInstance(1); // Initializes DigitalModule 1 as module
        i2c = module.getI2C(168); // Sets I2C address to send to as "168", which is "84" bit-shifted by one
        toSend[0] = i; // sets toSend as paramater "byte"
        i2c.transaction(toSend, 1, null, 0);
    } 
}
